[[CHiPPS_BLIS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fd542f4f70fb1da16da91297336bc453c21a621"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "007504bc52e3151836426b627279fa4deefe5d6c48a17554166933057a86890e"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.aarch64-linux-gnu-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0c84fc96c49a3beb17f95cf7902319ff2eef454"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "14197343cf9653899f84106e466b27007dcb73e875f2bece50de12b03b71723d"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.aarch64-linux-gnu-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd2f0f1b14bb8ffc45b771897f53f9aef65cc266"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "22be10201a19cd0935454828d028852d6f04118f16e170d74111c89c58c9a3a8"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.aarch64-linux-musl-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f4e3c1ddbc7a680a4e9ddf7bc41cbb5a325570c"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "dc00da1a667a7b3a9a653ae4cf95b44045c60fc0dd82c3921aabf86f93873542"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.aarch64-linux-musl-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "151d692437cb8584863def6a3b7387bb7b42c9b5"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "d7f3211b689fca4d91fddc6e10d6124c8cfa0e097507a5a01e6eebe01ced4a97"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa3288b929b89b82195b96a9fca663c07914d6d3"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "6d3724a2d211caa9d4f4709fd2d547233d5fbd64cf424762c05f51df1833992b"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a73360609d9ed1b623ccf3a41aff4e557a9125b4"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "d00c3c1566dd6b29ed2b2ad31651bab9566f2194c8d905c45c9a6263ab6280e7"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9edc5d5ec08ea2d5b52532bf80a0a581a05e142e"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "b95e5d2f5dcbad4bfcbe954f06dd3647a879d1aada54402fc688a3151ca2031f"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91327dbe39d4f94f829554af54809433efd66547"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "c09d6ee2b54058c3dea59b8e667215d33221cd621a329f0086d7a30ef28872c3"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.i686-linux-gnu-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "871ad2634775931c163a0647d66006bfc5ad34c3"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "17009f371e4632cfcd652c5bf7807bea6b30060de9d4e880165a2cee5f7c22de"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.i686-linux-gnu-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67b7730dac5f3b7f348050c87649799121fdba42"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "89f7b14b4c4c18c7d318f886909beebd9e4848bbf3058b90e5671cdb06f256c3"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.i686-linux-musl-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "198ce250886a33cec7210740f2e5867d18ba141d"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "f5ddf73e8585a30a1fba180206a69c1e1ba08bc38d8dfc1dabc7bcf8ec9f4c5f"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.i686-linux-musl-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "016530a8c8560686b467212e315748aeaf337f3c"
os = "windows"

    [[CHiPPS_BLIS.download]]
    sha256 = "5ff09b725973b0da3a9e9176a0b94f485c4ba671ffd88749c2deb65ffe77544f"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.i686-w64-mingw32-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8090b1ff578b1232859f39f6dd9770c7f7c29cad"
os = "windows"

    [[CHiPPS_BLIS.download]]
    sha256 = "eb0b1f63e195419817ce1719bc947d470449ab73cf090dfbdb46b758b44df045"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.i686-w64-mingw32-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae43f031071167d977a4f0bb61cf8322dc2c9514"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "180fd2abf79d8f2a9c1df547d1a7f8423c2af9d868d62e339e10a523c329bbdb"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e2f28cebb2ae7c0b9833b41afe79cc81df64874"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "0dcb7ff3916413277e080627cdd970aa7ce8f56a13ea6cdecda501f8adeb7722"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
git-tree-sha1 = "c394fc7710011a0071cd610ede42e53453e4fab4"
os = "macos"

    [[CHiPPS_BLIS.download]]
    sha256 = "c955b287aa183f9a5e7d5dac0c398d0e64ab2085379083d9ecddcad5e578da05"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-apple-darwin.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97f3e52c5dbe8ce57f932fdd0d7c8879826f05d1"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "43831b687c1e6e261a43e52dbc93b0e9930e95e209d67559e4341f1f920c13b5"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-linux-gnu-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1cd49f71dcf06bb30735bf36a6d33a7665fc78e"
libc = "glibc"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "dce0ac1d8a89365d6ca6c76f57ca187ac7a81c112ffcb47de57c5339343fc065"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-linux-gnu-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c496257239a8b836f5ccc8c6be9d916914e88c8c"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "504166dd35b9ae7c45aacbd238fed37d4491fbb1ba9d661fbbb86063ccc767f0"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-linux-musl-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "506125650aefc9aaacdb6039a3aec3aec900ac6a"
libc = "musl"
os = "linux"

    [[CHiPPS_BLIS.download]]
    sha256 = "a0696be54a7c37b5da61ac8ea9f9ef0b4b9b668477da581fcd0b6fab7c238fc8"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-linux-musl-cxx11.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "984372dc13743f9cf5a08eb229d9ea4b33ca3705"
os = "windows"

    [[CHiPPS_BLIS.download]]
    sha256 = "aeb6d9417f923dcd62fc2a6d9c7ca58075e91bd7c62759567f81927c62b44445"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-w64-mingw32-cxx03.tar.gz"
[[CHiPPS_BLIS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a2cb95f54bf1a1348bce91cb12a27079214648"
os = "windows"

    [[CHiPPS_BLIS.download]]
    sha256 = "9bb2c34f250a249dec18b7d7a579fb8f97edc4daddd8379e7af71d4f8b9647e6"
    url = "https://github.com/JuliaBinaryWrappers/CHiPPS_BLIS_jll.jl/releases/download/CHiPPS_BLIS-v0.9400.801+0/CHiPPS_BLIS.v0.9400.801.x86_64-w64-mingw32-cxx11.tar.gz"
